### ISSUE TITLE
Is v3.0.0-Preview still in preview?

### ISSUE THREAD

**Issue by DmitrySenin** [Azure/aspnet-redis-providers#100]
We really like the lock-free mode introduced in v3.0.0-Preview but the version's name implies that it is not stable enough or was not fully tested.
Could you, please, elaborate on this? Do you think it's fine to use v3.0.0-Preview in production?
Thank you in advance

**Comment by SiddharthChatrolaMs** [comment]
It was released as preview because it was a very big change and we wanted to be cautious. We haven't seen any major issue with this preview package. 

We are currently working on releasing a non-preview version of the same. It will take us sometime to do that though. You can start using this preview version and update to non-preview one once it is available.

**Comment by SiddharthChatrolaMs** [comment]
Non preview version is out now. https://www.nuget.org/packages/Microsoft.Web.RedisSessionStateProvider/3.0.1

**Comment by SiddharthChatrolaMs** [comment]
Please use https://www.nuget.org/packages/Microsoft.Web.RedisSessionStateProvider/3.0.2. As 3.0.1 has dll signing issue

**Comment by DmitrySenin** [comment]
@SiddharthChatrolaMs , thank you. Will do
