### ISSUE TITLE
Missing release notes for 4.x versions of nuget package

### ISSUE THREAD

**Issue by babakontheweb** [Azure/aspnet-redis-providers#129]
The release notes at https://github.com/Azure/aspnet-redis-providers/wiki/Release-Notes only go up to version 3.0.2 released to Nuget on 6/19/2018. Since then, two new versions of the Nuget package (4.0.0-preview and 4.0.1) have been pushed to Nuget but there are no associated release notes. 

What has changed since then? As it's a major version release, are there breaking changes?

**Comment by mapalan** [comment]
The release notes have been updated to include Session State Provider v4.0.1 and Output Cache Provider v3.0.1. The updated NuGet packages came from the branch AsyncProviders instead of from master (there are tags on the commits under that branch). The AsyncProviders branch has now been merged into master.

v4.0.1 of the Session State Provider requires .NET Framework 4.6.2.
