### ISSUE TITLE
Output Cache Provider Release Notes out of date

### ISSUE THREAD

**Issue by ellenhutchings** [Azure/aspnet-redis-providers#131]
The last note is for *v2.0.1-Preview* mentioning that there will be breaking changes. Since this package is now at v4.0.1 more information around updating this would be helpful.

**Comment by mapalan** [comment]
The release notes have been updated to include Session State Provider v4.0.1 and Output Cache Provider v3.0.1. The updated NuGet packages came from the branch AsyncProviders instead of from master (there are tags on the commits under that branch). The AsyncProviders branch has now been merged into master.

v3.0.1 of the Output Cache Provider requires .NET Framework 4.6.2 and uses the Async Output Cache Module.

**Comment by ellenhutchings** [comment]
Thanks!
