### ISSUE TITLE
5.0.0 Breaking Change - Why Change Cache Key Names?

### ISSUE THREAD

**Issue by DustinTheDev** [Azure/aspnet-redis-providers#188]
While added clarity for key names is great, there doesn't appear to be any substantial benefit from making this change.

Unfortunately, this change also has the effect of invalidating all sessions when upgrading, preventing it from being backward compatible and disrupting users without external migration efforts.

https://github.com/Azure/aspnet-redis-providers/pull/167/commits/790f764780e48dc5042ee8e89f9749ea3994a136

**Comment by DarthSonic** [comment]
Would suggest to be able to override that new key names optionally, so no session will be invalidated.

**Comment by stanleysmall-microsoft** [comment]
@DustinTheDev The version 5.0.0 would not be backwards compatible with previous versions even if we had not changed the cache key names. The underlying serialization method was changed. Namely, we treat session state objects as an atomic unit instead of breaking them into different keys. This change was necessary to remove unsafe serialization of generic objects. 

@DarthSonic While I appreciate the suggestion, the team will unlikely provide the option to change the key names unless we receive more requests from users for this feature.
