### ISSUE TITLE
Azure Cache for Redis giving Large response size than the key size stored in the cache causing the timeout issue.

### ISSUE THREAD

**Issue by tusharcts** [Azure/aspnet-redis-providers#192]
------------------------------------
We use the Redis Cache package library - SE.Redis-v2.6.96.30123 , Microsoft.Web.RedisSessionStateProvider – 5.0.0 , ASP.NET 4.8 – VB , to set and get session objects.
We save 25kB size of data in session, when writing the data to session it takes about 1.25 MB size and after that it shows 25KB size of data.

When running the below method are generating a large response size with ~1.25MB, even with only one small key with ~20KB in the cache:
 
![image](https://github.com/Azure/aspnet-redis-providers/assets/135574931/f68aaaf2-3f29-4526-845c-13f37591bce6)

Response size:
 
![image](https://github.com/Azure/aspnet-redis-providers/assets/135574931/2458f0ab-32b7-43e9-b0bd-d8e218d25dcd)

The questions are:
- why this is happening;
- what we can do to mitigate/resolve this.
------------------------------------------

**Comment by stanleysmall-microsoft** [comment]
One change with version 5 is that session state objects are treated as an atomic unit. When setting or getting a session state value, the entire session state object is serialized and sent to the cache. Previously items in the session state were stored in different keys of the cache. If the customer is migrating to v5, I would suggest they write and read the session state once instead of for each session object.
