### ISSUE TITLE
Support for ASP.Net Async SessionState?

### ISSUE THREAD

**Issue by palmej2** [Azure/aspnet-redis-providers#60]
Are there any plans to support the release of the ASP.Net Async SessionState provider?

**Comment by JonCole** [comment]
Are you referring to this:

Yes, this is something we are considering, but we don't yet have a timeline.

**Comment by palmej2** [comment]
I see. Thanks for the update.  I look forward to it!

**Comment by JonCole** [comment]
We have started the work to implement this.  I don't have a firm timeline for release, but I would guess it would be some time in the next couple of months.

**Comment by SiddharthChatrolaMs** [comment]
This is published now.
https://www.nuget.org/packages/Microsoft.Web.RedisSessionStateProvider/3.0.0-preview
https://github.com/Azure/aspnet-redis-providers/wiki/Release-Notes#v300-preview

**Comment by Leonardo-Ferreira** [comment]
@SiddharthChatrolaMs correct me if i'm wrong, but the RedisConnectionWrapper/StackExchangeClientConnection implementation seems to be using only the sync implementation of the redis... and in the end there's a `await Task.FromResult(0);`... no?

**Comment by JonCole** [comment]
@Leonardo-Ferreira Yes, that is true.  To be honest, the primary reason we picked up this work was to allow lock-free session state support, which is something we have had MANY people asking for.  The only way to support that was through this Async release.  We chose, at least in this first release, to stick with the sync code paths under the covers because we found that we got better performance with the sync code paths than the async code paths of StackExchange.Redis.  We agree that this is not ideal, but decided to go this route at least initially. 

If it is critical for your application to have truly async support, we can consider adding support for that.  If so, please provide details of why this is critical (even though I can guess at the reasons).  Thanks...

**Comment by Leonardo-Ferreira** [comment]
i forked this repo and i'm working on this... i expect to have something a week from today...
