### ISSUE TITLE
Add support for Redis Sentinel to RedisSessionStateProvider

### ISSUE THREAD

**Issue by colgreen** [Azure/aspnet-redis-providers#75]
RedisSessionStateProvider configuration allows only a single redis host name to be configured; this host is a single point of failure in non-azure installations. To allow use of the distributed high-availability features of redis it is necessary for this provider to support redis sentinel.

Also see this aspnet uservoice submission:

[Add support for Redis Sentinel to RedisSessionStateProvider](https://aspnet.uservoice.com/forums/41199-general-asp-net/suggestions/20009080-add-support-for-redis-sentinel-to-redissessionstat)

At the very least I think the README.md should be updated to be clear that this should not be used in non-azure scenarios if high-availability session state is required.

**Comment by guilhermelabigalini** [comment]
Yes, it works. I've implemented one sample, check at https://github.com/guilhermelabigalini/redis-cluster-example/tree/master/2-nodes 

Two servers servers with 2 sentinels, you can shutdown the master, the slave will be promoted to master and the asp.net application continues to run without issues.

**Comment by jphellemons** [comment]
Isn't Sentinel obsolete when running Redis on the premium plan? You will have persisted data and a 99.9 SLA. As I have found here: https://grantkillian.wordpress.com/2018/09/13/sitecores-sessiondictionarydata-class-saves-the-day/
you would need 3 Sentinel instances for 1 Redis server?

**Comment by mikevanoo** [comment]
@colgreen According to https://stackexchange.github.io/StackExchange.Redis/Configuration.html#tiebreakers-and-configuration-change-announcements, StackExchange.Redis automatically works out master/slave relationships. Perhaps this is because it pre-dates Sentinel? Or perhaps because it supports Cluster where you legitimately have multiple masters? Either way, it does mean that it doesn't necessarily have to talk to a Sentinel to ask what the master is.

The "Sentinel failover disconnection" section at https://redis.io/topics/sentinel-clients states that during failover existing connections are killed, forcing clients to re-work out a server to connect to, assuming the client is well behaved.

**Comment by mikevanoo** [comment]
Confirmed this works with a Sentinel setup BUT only if "retryTimeoutInMilliseconds" is greater than "down-after-milliseconds" in the Sentinel config.

See https://github.com/Azure/aspnet-redis-providers/issues/22#issuecomment-280741885

**Comment by mapalan** [comment]
Thanks @mikevanoo for confirming that it works. Since it does work, I am leaning towards closing this issue.

**Comment by mikevanoo** [comment]
@mapalan Yes, happy to close as for my purposes the config described in this issue works. As it happens, we went a different way with our Redis setup so didn't use Sentinel in the end anyway.

However, StackExchange.Redis now has first-class Sentinel support from v2.1 so that would be another route to look at if someone wished to.

**Comment by colgreen** [comment]
ok, thanks all. I originally raised this because I couldn't find a way to get ASP.NET session state backed by high availability redis nodes - the only option appeared to be a single redis node IP address. There clearly is support for that scenario now (and perhaps all along), and the underlying StackExchange.Redis package has moved on too.
