### ISSUE TITLE
upgrading to  'StackExchange.Redis.StrongName, Version=1.2.5

### ISSUE THREAD

**Issue by mehdymohajery** [Azure/aspnet-redis-providers#79]
The current nuget package mentions  StackExchange.Redis.StrongName' 1.2.1.0 or higher as dependency but if we upgrade to  StackExchange.Redis.StrongName 1.2.5 , we will get this exception:
Could not load file or assembly 'StackExchange.Redis.StrongName, Version=1.2.1.0

**Comment by woric** [comment]
We have had the same problem, and our solution was to downgrade
the StackExchange.Redis.StrongName package back to 1.2.1.

This was required because the Strong name package was automatically
upgraded to later than 1.2.1, but those newer versions are not compatible
with Dot net 4.0.

Is a pain, but that's what we've had to do.

See https://stackexchange.github.io/StackExchange.Redis/Release notes for
more details.

Woric

**Comment by SiddharthChatrolaMs** [comment]
We have just released preview version with some major changes that supports latest version of StackExchange.Redis.StrongName. You need to be on .net version 4.5.2 or higher.

https://www.nuget.org/packages/Microsoft.Web.RedisSessionStateProvider/3.0.0-preview
https://github.com/Azure/aspnet-redis-providers/wiki/Release-Notes#v300-preview
