### ISSUE TITLE
Write Lock remains after stopping App while debugging causing app to get stuck

### ISSUE THREAD

**Issue by mtschneiders** [Azure/aspnet-redis-providers#85]
Steps to reproduce:
 1 - Put a Breakpoint somewhere in the code
 2 - Open the Web App in Debug Mode
 3 - Make it hit the break point
 4 - Stop execution (Shift+F5)

The Write_Lock Key associated with that session will not be erased from redis.
When trying to open the app again using the same session, it gets stuck, probably because it is waiting for the lock to disappear.

Is there a way to tell the provider to clean the lock keys on the Application Start?

**Comment by Leonardo-Ferreira** [comment]
Clean it on app start is a not a good idea because of horizontal scale... application start will happen several times...

**Comment by SiddharthChatrolaMs** [comment]
This is expected behavior. According to ASP.NET, session should be locked during GetItemExclusive and should be releases in SetAndReleaseItemExclusive/ReleaseItemExclusive. If something goes wrong and request crashes in between then other request will wait for lock to expire (which will expire when request timeout hits).

Cleaning of lock is not advisable. If you want lock free version of session state provider try using 3.0.0-preview.
