### ISSUE TITLE
Provider must implement the class 'System.Web.SessionState.SessionStateStoreProviderBase'

### ISSUE THREAD

**Issue by dmarlow** [Azure/aspnet-redis-providers#99]
I'm trying the new v3 preview for lock free session and am seeing an error when trying to run my project.

![image](https://user-images.githubusercontent.com/2000510/38961989-0ab40bfc-4320-11e8-919e-94018f068316.png)

* I'm running on .NET 4.6.2
* I have `<add key="aspnet:AllowConcurrentRequestsPerSession" value="true"/>` in appSettings

My SessionState config in web.config:
```
<providers>
        <add name="RedisProvider"
                 type="Microsoft.Web.Redis.RedisSessionStateProvider" />
</providers>
```

**Comment by SiddharthChatrolaMs** [comment]
Can you verify that both NuGet packages are installed correctly "Microsoft.Web.RedisSessionStateProvider" and "Microsoft.AspNet.SessionState.SessionStateModule". From error it looks like App is not able to find the NuGet package for session state provider.

**Comment by dmarlow** [comment]
I see in my references that Microsoft.AspNet.SessionState.SessionStateModule is version 1.1.0.0 and referenced from `packages\Microsoft.AspNet.SessionState.SessionStateModule.1.1.0\lib\Net462\Microsoft.AspNet.SessionState.SessionStateModule.dll`

Microsoft.Web.RedisSessionStateProvider is version 3.0.0.0 and referenced from
`packages\Microsoft.Web.RedisSessionStateProvider.3.0.0-preview\lib\net462\Microsoft.Web.RedisSessionStateProvider.dll`

packages.config looks correct. I've also deleted all contents from `bin` folder and rebuilt to make sure.

**Comment by dmarlow** [comment]
Ok.. that was fun. Figured out the issue. On the new site, it worked, which was puzzling. Then, when I went back to the 2.2.6 version, it didn't work. Then, I noticed that there was a module configured, which wasn't configured in my original project.

```
<system.webServer>
    <modules>
      <remove name="Session" />
      <add name="Session" type="Microsoft.AspNet.SessionState.SessionStateModuleAsync, Microsoft.AspNet.SessionState.SessionStateModule, Version=1.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" preCondition="integratedMode" />
    </modules>
</system.webServer>
```

Adding/removing that based on the version being targeted works for me now! Apologies for the false alarm.

**Comment by Aleksanderis** [comment]
I have a little bit different, but probably related issue.
I'm receiving same error, double checked everything - and seems everything is in place. Latest "Microsoft.Web.RedisSessionStateProvider" and "Microsoft.AspNet.SessionState.SessionStateModule" are installed, webserver "Session" module with "integratedMode" is added to web.config, etc.

However, one important point - I don't receive this error all the time! It occurs highly randomly and seems like not on all instances at the same time (because it might be working for one user, but not for another, depending which instance is serving the user). After restarting the app - it usually returns to normal.

Summarizing - for me it looks like some race condition during app startup/configuration phase. What could be the problem with it?

**Comment by PaulVrugt** [comment]
@Aleksanderis did you ever find the cause? I seem to have a similar issue. After deploying my app service, I _sometimes_ get this error. Restarting the app service fixes the issue

**Comment by Aleksanderis** [comment]
> @Aleksanderis did you ever find the cause? I seem to have a similar issue. After deploying my app service, I _sometimes_ get this error. Restarting the app service fixes the issue

Unfortunately not really.. We just mitigated it by adding some additional workarounds - like trying to ping webapp instance and restart it if there is such error. In our solution it's being used by not highly critical app, so it's acceptable, but the issue is still weird..
